Vagrant.configure("2") do |config|

  config.vm.define "dc" do |cfg|
    cfg.vm.box = "../Boxes/windows_2016_virtualbox.box"
    cfg.vm.hostname = "dc"
    cfg.vm.boot_timeout = 600
    # use the plaintext WinRM transport and force it to use basic authentication.
    # NB this is needed because the default negotiate transport stops working
    #    after the domain controller is installed.
    #    see https://groups.google.com/forum/#!topic/vagrant-up/sZantuCM0q4
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.38.102", gateway: "192.168.38.1"

    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "192.168.38.102"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
#    cfg.vm.provision "shell", path: "scripts/populate-domain.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/configure-ou.ps1", privileged: true

    cfg.vm.provider "vmware_fusion" do |v, override|
      override.vm.box = "StefanScherer/windows_2016"
      v.vmx["displayname"] = "dc.labco.local"
      v.vmx["gui.fullscreenatpoweron"] = "FALSE"
      v.vmx["gui.viewModeAtPowerOn"] = "windowed"
      v.vmx["gui.fitguestusingnativedisplayresolution"] = "TRUE"
      v.memory = 2560
      v.cpus = 2
      v.gui = true
    end
  end


  config.vm.define "win10" do |cfg|
    cfg.vm.box = "../Boxes/windows_10_virtualbox.box"
    cfg.vm.hostname = "win10"
    cfg.vm.boot_timeout = 600
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.38.104", gateway: "192.168.38.1", dns: "192.168.38.102"

    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "-ip 192.168.38.104 -dns 192.168.38.102"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/MakeWindows10GreatAgain.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: true

    cfg.vm.provider "vmware_fusion" do |v, override|
      override.vm.box = "StefanScherer/windows_10"
      v.vmx["displayname"] = "win10.labco.local"
      v.vmx["gui.fullscreenatpoweron"] = "FALSE"
      v.vmx["gui.viewModeAtPowerOn"] = "windowed"
      v.vmx["gui.fitguestusingnativedisplayresolution"] = "TRUE"
      v.memory = 2048
      v.cpus = 1
      v.gui = true
    end
  end
end
